//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CommandLongRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CommandLong";
        public override string RosMessageName => k_RosMessageName;

        //  Generic COMMAND_LONG
        public bool broadcast;
        //  send this command in broadcast mode
        public ushort command;
        public byte confirmation;
        public float param1;
        public float param2;
        public float param3;
        public float param4;
        public float param5;
        //  x_lat
        public float param6;
        //  y_lon
        public float param7;
        //  z_alt

        public CommandLongRequest()
        {
            this.broadcast = false;
            this.command = 0;
            this.confirmation = 0;
            this.param1 = 0.0f;
            this.param2 = 0.0f;
            this.param3 = 0.0f;
            this.param4 = 0.0f;
            this.param5 = 0.0f;
            this.param6 = 0.0f;
            this.param7 = 0.0f;
        }

        public CommandLongRequest(bool broadcast, ushort command, byte confirmation, float param1, float param2, float param3, float param4, float param5, float param6, float param7)
        {
            this.broadcast = broadcast;
            this.command = command;
            this.confirmation = confirmation;
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.param4 = param4;
            this.param5 = param5;
            this.param6 = param6;
            this.param7 = param7;
        }

        public static CommandLongRequest Deserialize(MessageDeserializer deserializer) => new CommandLongRequest(deserializer);

        private CommandLongRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.broadcast);
            deserializer.Read(out this.command);
            deserializer.Read(out this.confirmation);
            deserializer.Read(out this.param1);
            deserializer.Read(out this.param2);
            deserializer.Read(out this.param3);
            deserializer.Read(out this.param4);
            deserializer.Read(out this.param5);
            deserializer.Read(out this.param6);
            deserializer.Read(out this.param7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.broadcast);
            serializer.Write(this.command);
            serializer.Write(this.confirmation);
            serializer.Write(this.param1);
            serializer.Write(this.param2);
            serializer.Write(this.param3);
            serializer.Write(this.param4);
            serializer.Write(this.param5);
            serializer.Write(this.param6);
            serializer.Write(this.param7);
        }

        public override string ToString()
        {
            return "CommandLongRequest: " +
            "\nbroadcast: " + broadcast.ToString() +
            "\ncommand: " + command.ToString() +
            "\nconfirmation: " + confirmation.ToString() +
            "\nparam1: " + param1.ToString() +
            "\nparam2: " + param2.ToString() +
            "\nparam3: " + param3.ToString() +
            "\nparam4: " + param4.ToString() +
            "\nparam5: " + param5.ToString() +
            "\nparam6: " + param6.ToString() +
            "\nparam7: " + param7.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
