//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CommandIntResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CommandInt";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        //  seems that this message don't produce andy COMMAND_ACK messages
        //  so no result field

        public CommandIntResponse()
        {
            this.success = false;
        }

        public CommandIntResponse(bool success)
        {
            this.success = success;
        }

        public static CommandIntResponse Deserialize(MessageDeserializer deserializer) => new CommandIntResponse(deserializer);

        private CommandIntResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "CommandIntResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
