//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CommandHomeRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CommandHome";
        public override string RosMessageName => k_RosMessageName;

        //  request set new home position
        public bool current_gps;
        public float yaw;
        public float latitude;
        public float longitude;
        public float altitude;

        public CommandHomeRequest()
        {
            this.current_gps = false;
            this.yaw = 0.0f;
            this.latitude = 0.0f;
            this.longitude = 0.0f;
            this.altitude = 0.0f;
        }

        public CommandHomeRequest(bool current_gps, float yaw, float latitude, float longitude, float altitude)
        {
            this.current_gps = current_gps;
            this.yaw = yaw;
            this.latitude = latitude;
            this.longitude = longitude;
            this.altitude = altitude;
        }

        public static CommandHomeRequest Deserialize(MessageDeserializer deserializer) => new CommandHomeRequest(deserializer);

        private CommandHomeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_gps);
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
            deserializer.Read(out this.altitude);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_gps);
            serializer.Write(this.yaw);
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
            serializer.Write(this.altitude);
        }

        public override string ToString()
        {
            return "CommandHomeRequest: " +
            "\ncurrent_gps: " + current_gps.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString() +
            "\naltitude: " + altitude.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
