//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CommandAckRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CommandAck";
        public override string RosMessageName => k_RosMessageName;

        //  Generic COMMAND_ACK
        public ushort command;
        public byte result;
        public byte progress;
        public uint result_param2;

        public CommandAckRequest()
        {
            this.command = 0;
            this.result = 0;
            this.progress = 0;
            this.result_param2 = 0;
        }

        public CommandAckRequest(ushort command, byte result, byte progress, uint result_param2)
        {
            this.command = command;
            this.result = result;
            this.progress = progress;
            this.result_param2 = result_param2;
        }

        public static CommandAckRequest Deserialize(MessageDeserializer deserializer) => new CommandAckRequest(deserializer);

        private CommandAckRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
            deserializer.Read(out this.result);
            deserializer.Read(out this.progress);
            deserializer.Read(out this.result_param2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
            serializer.Write(this.result);
            serializer.Write(this.progress);
            serializer.Write(this.result_param2);
        }

        public override string ToString()
        {
            return "CommandAckRequest: " +
            "\ncommand: " + command.ToString() +
            "\nresult: " + result.ToString() +
            "\nprogress: " + progress.ToString() +
            "\nresult_param2: " + result_param2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
