//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CommandVtolTransitionRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CommandVtolTransition";
        public override string RosMessageName => k_RosMessageName;

        //  MAVLink command: DO_VTOL_TRANSITION
        //  https://mavlink.io/en/messages/common.html#MAV_CMD_DO_VTOL_TRANSITION
        public Std.HeaderMsg header;
        //  MAV_VTOL_STATE
        public const byte STATE_MC = 3;
        public const byte STATE_FW = 4;
        public byte state;
        //  See enum MAV_VTOL_STATE.

        public CommandVtolTransitionRequest()
        {
            this.header = new Std.HeaderMsg();
            this.state = 0;
        }

        public CommandVtolTransitionRequest(Std.HeaderMsg header, byte state)
        {
            this.header = header;
            this.state = state;
        }

        public static CommandVtolTransitionRequest Deserialize(MessageDeserializer deserializer) => new CommandVtolTransitionRequest(deserializer);

        private CommandVtolTransitionRequest(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "CommandVtolTransitionRequest: " +
            "\nheader: " + header.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
