//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CommandBoolRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CommandBool";
        public override string RosMessageName => k_RosMessageName;

        //  Common type for switch commands
        public bool value;

        public CommandBoolRequest()
        {
            this.value = false;
        }

        public CommandBoolRequest(bool value)
        {
            this.value = value;
        }

        public static CommandBoolRequest Deserialize(MessageDeserializer deserializer) => new CommandBoolRequest(deserializer);

        private CommandBoolRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "CommandBoolRequest: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
