//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CommandTriggerIntervalRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CommandTriggerInterval";
        public override string RosMessageName => k_RosMessageName;

        //  Type for controlling camera trigger interval and integration time
        public float cycle_time;
        //  Trigger cycle_time (interval between to triggers) - set to 0 to ignore command
        public float integration_time;
        //  Camera shutter integration_time - set to 0 to ignore command

        public CommandTriggerIntervalRequest()
        {
            this.cycle_time = 0.0f;
            this.integration_time = 0.0f;
        }

        public CommandTriggerIntervalRequest(float cycle_time, float integration_time)
        {
            this.cycle_time = cycle_time;
            this.integration_time = integration_time;
        }

        public static CommandTriggerIntervalRequest Deserialize(MessageDeserializer deserializer) => new CommandTriggerIntervalRequest(deserializer);

        private CommandTriggerIntervalRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cycle_time);
            deserializer.Read(out this.integration_time);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cycle_time);
            serializer.Write(this.integration_time);
        }

        public override string ToString()
        {
            return "CommandTriggerIntervalRequest: " +
            "\ncycle_time: " + cycle_time.ToString() +
            "\nintegration_time: " + integration_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
