//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CommandBoolResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CommandBool";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public byte result;

        public CommandBoolResponse()
        {
            this.success = false;
            this.result = 0;
        }

        public CommandBoolResponse(bool success, byte result)
        {
            this.success = success;
            this.result = result;
        }

        public static CommandBoolResponse Deserialize(MessageDeserializer deserializer) => new CommandBoolResponse(deserializer);

        private CommandBoolResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "CommandBoolResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
