//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class EndpointDelResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/EndpointDel";
        public override string RosMessageName => k_RosMessageName;

        public bool successful;

        public EndpointDelResponse()
        {
            this.successful = false;
        }

        public EndpointDelResponse(bool successful)
        {
            this.successful = successful;
        }

        public static EndpointDelResponse Deserialize(MessageDeserializer deserializer) => new EndpointDelResponse(deserializer);

        private EndpointDelResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.successful);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.successful);
        }

        public override string ToString()
        {
            return "EndpointDelResponse: " +
            "\nsuccessful: " + successful.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
