//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class EndpointAddResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/EndpointAdd";
        public override string RosMessageName => k_RosMessageName;

        public bool successful;
        //  true if endpoint added and opened
        public string reason;
        //  returns error description if open fails
        public uint id;
        //  ID of new endpoint, should be > 0 if endpoint created

        public EndpointAddResponse()
        {
            this.successful = false;
            this.reason = "";
            this.id = 0;
        }

        public EndpointAddResponse(bool successful, string reason, uint id)
        {
            this.successful = successful;
            this.reason = reason;
            this.id = id;
        }

        public static EndpointAddResponse Deserialize(MessageDeserializer deserializer) => new EndpointAddResponse(deserializer);

        private EndpointAddResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.successful);
            deserializer.Read(out this.reason);
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.successful);
            serializer.Write(this.reason);
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "EndpointAddResponse: " +
            "\nsuccessful: " + successful.ToString() +
            "\nreason: " + reason.ToString() +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
