//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class EndpointAddRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/EndpointAdd";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Adds endpoint to router
        // 
        public const byte TYPE_FCU = 0;
        public const byte TYPE_GCS = 1;
        public const byte TYPE_UAS = 2;
        public string url;
        //  mavconn URL or topic prefix for TYPE_UAS
        public byte type;
        //  should be set to one of the TYPE_xxx

        public EndpointAddRequest()
        {
            this.url = "";
            this.type = 0;
        }

        public EndpointAddRequest(string url, byte type)
        {
            this.url = url;
            this.type = type;
        }

        public static EndpointAddRequest Deserialize(MessageDeserializer deserializer) => new EndpointAddRequest(deserializer);

        private EndpointAddRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.url);
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.url);
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "EndpointAddRequest: " +
            "\nurl: " + url.ToString() +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
