//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class EndpointDelRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/EndpointDel";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Removes endpoint from router
        // 
        public const byte TYPE_FCU = 0;
        public const byte TYPE_GCS = 1;
        public const byte TYPE_UAS = 2;
        //  delete by ID, leave 0 for second option
        public uint id;
        //  delete by url+type pair
        public string url;
        public byte type;

        public EndpointDelRequest()
        {
            this.id = 0;
            this.url = "";
            this.type = 0;
        }

        public EndpointDelRequest(uint id, string url, byte type)
        {
            this.id = id;
            this.url = url;
            this.type = type;
        }

        public static EndpointDelRequest Deserialize(MessageDeserializer deserializer) => new EndpointDelRequest(deserializer);

        private EndpointDelRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.url);
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.url);
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "EndpointDelRequest: " +
            "\nid: " + id.ToString() +
            "\nurl: " + url.ToString() +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
