//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileOpenRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileOpen";
        public override string RosMessageName => k_RosMessageName;

        //  FTP::Open
        // 
        //  :file_path:	used as session id in read/write/close services
        //  :size:	file size returned for MODE_READ
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public const byte MODE_READ = 0; //  open for read
        public const byte MODE_WRITE = 1; //  open for write
        public const byte MODE_CREATE = 2; //  do creat()
        public string file_path;
        public byte mode;

        public FileOpenRequest()
        {
            this.file_path = "";
            this.mode = 0;
        }

        public FileOpenRequest(string file_path, byte mode)
        {
            this.file_path = file_path;
            this.mode = mode;
        }

        public static FileOpenRequest Deserialize(MessageDeserializer deserializer) => new FileOpenRequest(deserializer);

        private FileOpenRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.file_path);
            deserializer.Read(out this.mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.file_path);
            serializer.Write(this.mode);
        }

        public override string ToString()
        {
            return "FileOpenRequest: " +
            "\nfile_path: " + file_path.ToString() +
            "\nmode: " + mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
