//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileListResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileList";
        public override string RosMessageName => k_RosMessageName;

        public FileEntryMsg[] list;
        public bool success;
        public int r_errno;

        public FileListResponse()
        {
            this.list = new FileEntryMsg[0];
            this.success = false;
            this.r_errno = 0;
        }

        public FileListResponse(FileEntryMsg[] list, bool success, int r_errno)
        {
            this.list = list;
            this.success = success;
            this.r_errno = r_errno;
        }

        public static FileListResponse Deserialize(MessageDeserializer deserializer) => new FileListResponse(deserializer);

        private FileListResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.list, FileEntryMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.success);
            deserializer.Read(out this.r_errno);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.list);
            serializer.Write(this.list);
            serializer.Write(this.success);
            serializer.Write(this.r_errno);
        }

        public override string ToString()
        {
            return "FileListResponse: " +
            "\nlist: " + System.String.Join(", ", list.ToList()) +
            "\nsuccess: " + success.ToString() +
            "\nr_errno: " + r_errno.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
