//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileRenameRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileRename";
        public override string RosMessageName => k_RosMessageName;

        //  FTP::Rename
        // 
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public string old_path;
        public string new_path;

        public FileRenameRequest()
        {
            this.old_path = "";
            this.new_path = "";
        }

        public FileRenameRequest(string old_path, string new_path)
        {
            this.old_path = old_path;
            this.new_path = new_path;
        }

        public static FileRenameRequest Deserialize(MessageDeserializer deserializer) => new FileRenameRequest(deserializer);

        private FileRenameRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.old_path);
            deserializer.Read(out this.new_path);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.old_path);
            serializer.Write(this.new_path);
        }

        public override string ToString()
        {
            return "FileRenameRequest: " +
            "\nold_path: " + old_path.ToString() +
            "\nnew_path: " + new_path.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
