//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileTruncateRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileTruncate";
        public override string RosMessageName => k_RosMessageName;

        //  FTP::Truncate
        // 
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public string file_path;
        public ulong length;

        public FileTruncateRequest()
        {
            this.file_path = "";
            this.length = 0;
        }

        public FileTruncateRequest(string file_path, ulong length)
        {
            this.file_path = file_path;
            this.length = length;
        }

        public static FileTruncateRequest Deserialize(MessageDeserializer deserializer) => new FileTruncateRequest(deserializer);

        private FileTruncateRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.file_path);
            deserializer.Read(out this.length);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.file_path);
            serializer.Write(this.length);
        }

        public override string ToString()
        {
            return "FileTruncateRequest: " +
            "\nfile_path: " + file_path.ToString() +
            "\nlength: " + length.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
