//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileChecksumResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileChecksum";
        public override string RosMessageName => k_RosMessageName;

        public uint crc32;
        public bool success;
        public int r_errno;

        public FileChecksumResponse()
        {
            this.crc32 = 0;
            this.success = false;
            this.r_errno = 0;
        }

        public FileChecksumResponse(uint crc32, bool success, int r_errno)
        {
            this.crc32 = crc32;
            this.success = success;
            this.r_errno = r_errno;
        }

        public static FileChecksumResponse Deserialize(MessageDeserializer deserializer) => new FileChecksumResponse(deserializer);

        private FileChecksumResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.crc32);
            deserializer.Read(out this.success);
            deserializer.Read(out this.r_errno);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.crc32);
            serializer.Write(this.success);
            serializer.Write(this.r_errno);
        }

        public override string ToString()
        {
            return "FileChecksumResponse: " +
            "\ncrc32: " + crc32.ToString() +
            "\nsuccess: " + success.ToString() +
            "\nr_errno: " + r_errno.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
