//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileRemoveDirResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileRemoveDir";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public int r_errno;

        public FileRemoveDirResponse()
        {
            this.success = false;
            this.r_errno = 0;
        }

        public FileRemoveDirResponse(bool success, int r_errno)
        {
            this.success = success;
            this.r_errno = r_errno;
        }

        public static FileRemoveDirResponse Deserialize(MessageDeserializer deserializer) => new FileRemoveDirResponse(deserializer);

        private FileRemoveDirResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.r_errno);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.r_errno);
        }

        public override string ToString()
        {
            return "FileRemoveDirResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nr_errno: " + r_errno.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
