//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileChecksumRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileChecksum";
        public override string RosMessageName => k_RosMessageName;

        //  FTP::Checksum
        // 
        //  :file_path:	file to calculate checksum
        //  :crc32:	file checksum
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public string file_path;

        public FileChecksumRequest()
        {
            this.file_path = "";
        }

        public FileChecksumRequest(string file_path)
        {
            this.file_path = file_path;
        }

        public static FileChecksumRequest Deserialize(MessageDeserializer deserializer) => new FileChecksumRequest(deserializer);

        private FileChecksumRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.file_path);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.file_path);
        }

        public override string ToString()
        {
            return "FileChecksumRequest: " +
            "\nfile_path: " + file_path.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
