//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileWriteRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileWrite";
        public override string RosMessageName => k_RosMessageName;

        //  FTP::Write
        // 
        //  Call FTP::Open first.
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public string file_path;
        public ulong offset;
        public byte[] data;

        public FileWriteRequest()
        {
            this.file_path = "";
            this.offset = 0;
            this.data = new byte[0];
        }

        public FileWriteRequest(string file_path, ulong offset, byte[] data)
        {
            this.file_path = file_path;
            this.offset = offset;
            this.data = data;
        }

        public static FileWriteRequest Deserialize(MessageDeserializer deserializer) => new FileWriteRequest(deserializer);

        private FileWriteRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.file_path);
            deserializer.Read(out this.offset);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.file_path);
            serializer.Write(this.offset);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "FileWriteRequest: " +
            "\nfile_path: " + file_path.ToString() +
            "\noffset: " + offset.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
