//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileListRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileList";
        public override string RosMessageName => k_RosMessageName;

        //  FTP::List
        // 
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public string dir_path;

        public FileListRequest()
        {
            this.dir_path = "";
        }

        public FileListRequest(string dir_path)
        {
            this.dir_path = dir_path;
        }

        public static FileListRequest Deserialize(MessageDeserializer deserializer) => new FileListRequest(deserializer);

        private FileListRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.dir_path);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.dir_path);
        }

        public override string ToString()
        {
            return "FileListRequest: " +
            "\ndir_path: " + dir_path.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
