//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileOpenResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileOpen";
        public override string RosMessageName => k_RosMessageName;

        public uint size;
        public bool success;
        public int r_errno;

        public FileOpenResponse()
        {
            this.size = 0;
            this.success = false;
            this.r_errno = 0;
        }

        public FileOpenResponse(uint size, bool success, int r_errno)
        {
            this.size = size;
            this.success = success;
            this.r_errno = r_errno;
        }

        public static FileOpenResponse Deserialize(MessageDeserializer deserializer) => new FileOpenResponse(deserializer);

        private FileOpenResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.size);
            deserializer.Read(out this.success);
            deserializer.Read(out this.r_errno);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.size);
            serializer.Write(this.success);
            serializer.Write(this.r_errno);
        }

        public override string ToString()
        {
            return "FileOpenResponse: " +
            "\nsize: " + size.ToString() +
            "\nsuccess: " + success.ToString() +
            "\nr_errno: " + r_errno.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
