//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileReadRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileRead";
        public override string RosMessageName => k_RosMessageName;

        //  FTP::Read
        // 
        //  Call FTP::Open first.
        //  :success:	indicates success end of request
        //  :r_errno:	remote errno if applicapable
        public string file_path;
        public ulong offset;
        public ulong size;

        public FileReadRequest()
        {
            this.file_path = "";
            this.offset = 0;
            this.size = 0;
        }

        public FileReadRequest(string file_path, ulong offset, ulong size)
        {
            this.file_path = file_path;
            this.offset = offset;
            this.size = size;
        }

        public static FileReadRequest Deserialize(MessageDeserializer deserializer) => new FileReadRequest(deserializer);

        private FileReadRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.file_path);
            deserializer.Read(out this.offset);
            deserializer.Read(out this.size);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.file_path);
            serializer.Write(this.offset);
            serializer.Write(this.size);
        }

        public override string ToString()
        {
            return "FileReadRequest: " +
            "\nfile_path: " + file_path.ToString() +
            "\noffset: " + offset.ToString() +
            "\nsize: " + size.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
