//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class GimbalGetInformationRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/GimbalGetInformation";
        public override string RosMessageName => k_RosMessageName;

        //  MAVLink command: MAV_CMD_REQUEST_MESSAGE
        //  https://mavlink.io/en/messages/common.html#MAV_CMD_REQUEST_MESSAGE
        //  Specifically used to request Information messages from Gimbal Device and Gimbal Manager
        //  https://mavlink.io/en/messages/common.html#GIMBAL_MANAGER_INFORMATION
        //  https://mavlink.io/en/messages/common.html#GIMBAL_DEVICE_INFORMATION

        public GimbalGetInformationRequest()
        {
        }
        public static GimbalGetInformationRequest Deserialize(MessageDeserializer deserializer) => new GimbalGetInformationRequest(deserializer);

        private GimbalGetInformationRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GimbalGetInformationRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
