//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class LogRequestListRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/LogRequestList";
        public override string RosMessageName => k_RosMessageName;

        //  Request a list of available logs
        // 
        //   :start: - first log id (0 for first available)
        //   :end: - last log id (0xffff for last available)
        public ushort start;
        public ushort end;

        public LogRequestListRequest()
        {
            this.start = 0;
            this.end = 0;
        }

        public LogRequestListRequest(ushort start, ushort end)
        {
            this.start = start;
            this.end = end;
        }

        public static LogRequestListRequest Deserialize(MessageDeserializer deserializer) => new LogRequestListRequest(deserializer);

        private LogRequestListRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.start);
            deserializer.Read(out this.end);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start);
            serializer.Write(this.end);
        }

        public override string ToString()
        {
            return "LogRequestListRequest: " +
            "\nstart: " + start.ToString() +
            "\nend: " + end.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
