//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class LogRequestListResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/LogRequestList";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public LogRequestListResponse()
        {
            this.success = false;
        }

        public LogRequestListResponse(bool success)
        {
            this.success = success;
        }

        public static LogRequestListResponse Deserialize(MessageDeserializer deserializer) => new LogRequestListResponse(deserializer);

        private LogRequestListResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "LogRequestListResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
