//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class LogRequestEndRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/LogRequestEnd";
        public override string RosMessageName => k_RosMessageName;

        //  Stop log transfer and resume normal logging

        public LogRequestEndRequest()
        {
        }
        public static LogRequestEndRequest Deserialize(MessageDeserializer deserializer) => new LogRequestEndRequest(deserializer);

        private LogRequestEndRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "LogRequestEndRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
