//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class MessageIntervalRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/MessageInterval";
        public override string RosMessageName => k_RosMessageName;

        //  sets message interval
        //  See MAV_CMD_SET_MESSAGE_INTERVAL
        public uint message_id;
        public float message_rate;

        public MessageIntervalRequest()
        {
            this.message_id = 0;
            this.message_rate = 0.0f;
        }

        public MessageIntervalRequest(uint message_id, float message_rate)
        {
            this.message_id = message_id;
            this.message_rate = message_rate;
        }

        public static MessageIntervalRequest Deserialize(MessageDeserializer deserializer) => new MessageIntervalRequest(deserializer);

        private MessageIntervalRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.message_id);
            deserializer.Read(out this.message_rate);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.message_id);
            serializer.Write(this.message_rate);
        }

        public override string ToString()
        {
            return "MessageIntervalRequest: " +
            "\nmessage_id: " + message_id.ToString() +
            "\nmessage_rate: " + message_rate.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
