//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ParamPullResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ParamPull";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public uint param_received;

        public ParamPullResponse()
        {
            this.success = false;
            this.param_received = 0;
        }

        public ParamPullResponse(bool success, uint param_received)
        {
            this.success = success;
            this.param_received = param_received;
        }

        public static ParamPullResponse Deserialize(MessageDeserializer deserializer) => new ParamPullResponse(deserializer);

        private ParamPullResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.param_received);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.param_received);
        }

        public override string ToString()
        {
            return "ParamPullResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nparam_received: " + param_received.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
