//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ParamPullRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ParamPull";
        public override string RosMessageName => k_RosMessageName;

        //  Request parameters from device
        // 
        //  Returns success status and param_recived count
        public bool force_pull;

        public ParamPullRequest()
        {
            this.force_pull = false;
        }

        public ParamPullRequest(bool force_pull)
        {
            this.force_pull = force_pull;
        }

        public static ParamPullRequest Deserialize(MessageDeserializer deserializer) => new ParamPullRequest(deserializer);

        private ParamPullRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.force_pull);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.force_pull);
        }

        public override string ToString()
        {
            return "ParamPullRequest: " +
            "\nforce_pull: " + force_pull.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
