//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ParamPushResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ParamPush";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public uint param_transfered;

        public ParamPushResponse()
        {
            this.success = false;
            this.param_transfered = 0;
        }

        public ParamPushResponse(bool success, uint param_transfered)
        {
            this.success = success;
            this.param_transfered = param_transfered;
        }

        public static ParamPushResponse Deserialize(MessageDeserializer deserializer) => new ParamPushResponse(deserializer);

        private ParamPushResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.param_transfered);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.param_transfered);
        }

        public override string ToString()
        {
            return "ParamPushResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nparam_transfered: " + param_transfered.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
