//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ParamGetResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ParamGet";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public ParamValueMsg value;

        public ParamGetResponse()
        {
            this.success = false;
            this.value = new ParamValueMsg();
        }

        public ParamGetResponse(bool success, ParamValueMsg value)
        {
            this.success = success;
            this.value = value;
        }

        public static ParamGetResponse Deserialize(MessageDeserializer deserializer) => new ParamGetResponse(deserializer);

        private ParamGetResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            this.value = ParamValueMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "ParamGetResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
