//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ParamSetRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ParamSet";
        public override string RosMessageName => k_RosMessageName;

        //  Request set parameter value
        //  XXX DEPRECATED: replaced by ParamSetV2
        public string param_id;
        public ParamValueMsg value;

        public ParamSetRequest()
        {
            this.param_id = "";
            this.value = new ParamValueMsg();
        }

        public ParamSetRequest(string param_id, ParamValueMsg value)
        {
            this.param_id = param_id;
            this.value = value;
        }

        public static ParamSetRequest Deserialize(MessageDeserializer deserializer) => new ParamSetRequest(deserializer);

        private ParamSetRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.param_id);
            this.value = ParamValueMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.param_id);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "ParamSetRequest: " +
            "\nparam_id: " + param_id.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
