//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class SetMavFrameRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/SetMavFrame";
        public override string RosMessageName => k_RosMessageName;

        //  Set MAV_FRAME for setpoints
        //  XXX DEPRECATED
        //  [[[cog:
        //  import mavros_cog
        //  mavros_cog.idl_decl_enum('MAV_FRAME', 'FRAME_')
        //  ]]]
        //  MAV_FRAME
        public const byte FRAME_GLOBAL = 0; //  Global (WGS84) coordinate frame + altitude relative to mean sea level (MSL).
        public const byte FRAME_LOCAL_NED = 1; //  NED local tangent frame (x: North, y: East, z: Down) with origin fixed relative to earth.
        public const byte FRAME_MISSION = 2; //  NOT a coordinate frame, indicates a mission command.
        public const byte FRAME_GLOBAL_RELATIVE_ALT = 3; //  Global (WGS84) coordinate frame + altitude relative to the home position.
        public const byte FRAME_LOCAL_ENU = 4; //  ENU local tangent frame (x: East, y: North, z: Up) with origin fixed relative to earth.
        public const byte FRAME_GLOBAL_INT = 5; //  Global (WGS84) coordinate frame (scaled) + altitude relative to mean sea level (MSL).
        public const byte FRAME_GLOBAL_RELATIVE_ALT_INT = 6; //  Global (WGS84) coordinate frame (scaled) + altitude relative to the home position.
        public const byte FRAME_LOCAL_OFFSET_NED = 7; //  NED local tangent frame (x: North, y: East, z: Down) with origin that travels with the vehicle.
        public const byte FRAME_BODY_NED = 8; //  Same as MAV_FRAME_LOCAL_NED when used to represent position values. Same as MAV_FRAME_BODY_FRD when used with velocity/acceleration values.
        public const byte FRAME_BODY_OFFSET_NED = 9; //  This is the same as MAV_FRAME_BODY_FRD.
        public const byte FRAME_GLOBAL_TERRAIN_ALT = 10; //  Global (WGS84) coordinate frame with AGL altitude (altitude at ground level).
        public const byte FRAME_GLOBAL_TERRAIN_ALT_INT = 11; //  Global (WGS84) coordinate frame (scaled) with AGL altitude (altitude at ground level).
        public const byte FRAME_BODY_FRD = 12; //  FRD local frame aligned to the vehicle's attitude (x: Forward, y: Right, z: Down) with an origin that travels with vehicle.
        public const byte FRAME_RESERVED_13 = 13; //  MAV_FRAME_BODY_FLU - Body fixed frame of reference, Z-up (x: Forward, y: Left, z: Up).
        public const byte FRAME_RESERVED_14 = 14; //  MAV_FRAME_MOCAP_NED - Odometry local coordinate frame of data given by a motion capture system, Z-down (x: North, y: East, z: Down).
        public const byte FRAME_RESERVED_15 = 15; //  MAV_FRAME_MOCAP_ENU - Odometry local coordinate frame of data given by a motion capture system, Z-up (x: East, y: North, z: Up).
        public const byte FRAME_RESERVED_16 = 16; //  MAV_FRAME_VISION_NED - Odometry local coordinate frame of data given by a vision estimation system, Z-down (x: North, y: East, z: Down).
        public const byte FRAME_RESERVED_17 = 17; //  MAV_FRAME_VISION_ENU - Odometry local coordinate frame of data given by a vision estimation system, Z-up (x: East, y: North, z: Up).
        public const byte FRAME_RESERVED_18 = 18; //  MAV_FRAME_ESTIM_NED - Odometry local coordinate frame of data given by an estimator running onboard the vehicle, Z-down (x: North, y: East, z: Down).
        public const byte FRAME_RESERVED_19 = 19; //  MAV_FRAME_ESTIM_ENU - Odometry local coordinate frame of data given by an estimator running onboard the vehicle, Z-up (x: East, y: North, z: Up).
        public const byte FRAME_LOCAL_FRD = 20; //  FRD local tangent frame (x: Forward, y: Right, z: Down) with origin fixed relative to earth. The forward axis is aligned to the front of the vehicle in the horizontal plane.
        public const byte FRAME_LOCAL_FLU = 21; //  FLU local tangent frame (x: Forward, y: Left, z: Up) with origin fixed relative to earth. The forward axis is aligned to the front of the vehicle in the horizontal plane.
        //  [[[end]]] (sum: kOvJDYd0kF)
        public byte mav_frame;

        public SetMavFrameRequest()
        {
            this.mav_frame = 0;
        }

        public SetMavFrameRequest(byte mav_frame)
        {
            this.mav_frame = mav_frame;
        }

        public static SetMavFrameRequest Deserialize(MessageDeserializer deserializer) => new SetMavFrameRequest(deserializer);

        private SetMavFrameRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mav_frame);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mav_frame);
        }

        public override string ToString()
        {
            return "SetMavFrameRequest: " +
            "\nmav_frame: " + mav_frame.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
