//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class SetMavFrameResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/SetMavFrame";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public SetMavFrameResponse()
        {
            this.success = false;
        }

        public SetMavFrameResponse(bool success)
        {
            this.success = success;
        }

        public static SetMavFrameResponse Deserialize(MessageDeserializer deserializer) => new SetMavFrameResponse(deserializer);

        private SetMavFrameResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "SetMavFrameResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
