//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class SetModeResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/SetMode";
        public override string RosMessageName => k_RosMessageName;

        public bool mode_sent;
        //  Mode known/parsed correctly and SET_MODE are sent

        public SetModeResponse()
        {
            this.mode_sent = false;
        }

        public SetModeResponse(bool mode_sent)
        {
            this.mode_sent = mode_sent;
        }

        public static SetModeResponse Deserialize(MessageDeserializer deserializer) => new SetModeResponse(deserializer);

        private SetModeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode_sent);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode_sent);
        }

        public override string ToString()
        {
            return "SetModeResponse: " +
            "\nmode_sent: " + mode_sent.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
