//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class SetModeRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/SetMode";
        public override string RosMessageName => k_RosMessageName;

        //  set FCU mode
        // 
        //  Known custom modes listed here:
        //  http://wiki.ros.org/mavros/CustomModes
        //  basic modes from MAV_MODE
        public const byte MAV_MODE_PREFLIGHT = 0;
        public const byte MAV_MODE_STABILIZE_DISARMED = 80;
        public const byte MAV_MODE_STABILIZE_ARMED = 208;
        public const byte MAV_MODE_MANUAL_DISARMED = 64;
        public const byte MAV_MODE_MANUAL_ARMED = 192;
        public const byte MAV_MODE_GUIDED_DISARMED = 88;
        public const byte MAV_MODE_GUIDED_ARMED = 216;
        public const byte MAV_MODE_AUTO_DISARMED = 92;
        public const byte MAV_MODE_AUTO_ARMED = 220;
        public const byte MAV_MODE_TEST_DISARMED = 66;
        public const byte MAV_MODE_TEST_ARMED = 194;
        public byte base_mode;
        //  filled by MAV_MODE enum value or 0 if custom_mode != ''
        public string custom_mode;
        //  string mode representation or integer

        public SetModeRequest()
        {
            this.base_mode = 0;
            this.custom_mode = "";
        }

        public SetModeRequest(byte base_mode, string custom_mode)
        {
            this.base_mode = base_mode;
            this.custom_mode = custom_mode;
        }

        public static SetModeRequest Deserialize(MessageDeserializer deserializer) => new SetModeRequest(deserializer);

        private SetModeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.base_mode);
            deserializer.Read(out this.custom_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.base_mode);
            serializer.Write(this.custom_mode);
        }

        public override string ToString()
        {
            return "SetModeRequest: " +
            "\nbase_mode: " + base_mode.ToString() +
            "\ncustom_mode: " + custom_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
