//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class VehicleInfoGetResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/VehicleInfoGet";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public VehicleInfoMsg[] vehicles;

        public VehicleInfoGetResponse()
        {
            this.success = false;
            this.vehicles = new VehicleInfoMsg[0];
        }

        public VehicleInfoGetResponse(bool success, VehicleInfoMsg[] vehicles)
        {
            this.success = success;
            this.vehicles = vehicles;
        }

        public static VehicleInfoGetResponse Deserialize(MessageDeserializer deserializer) => new VehicleInfoGetResponse(deserializer);

        private VehicleInfoGetResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.vehicles, VehicleInfoMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.WriteLength(this.vehicles);
            serializer.Write(this.vehicles);
        }

        public override string ToString()
        {
            return "VehicleInfoGetResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nvehicles: " + System.String.Join(", ", vehicles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
