//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class VehicleInfoGetRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/VehicleInfoGet";
        public override string RosMessageName => k_RosMessageName;

        //  Request the Vehicle Info
        //  use this to request the current target sysid / compid defined in mavros
        //  set get_all = True to request all available vehicles
        public const byte GET_MY_SYSID = 0;
        public const byte GET_MY_COMPID = 0;
        public byte sysid;
        public byte compid;
        public bool get_all;

        public VehicleInfoGetRequest()
        {
            this.sysid = 0;
            this.compid = 0;
            this.get_all = false;
        }

        public VehicleInfoGetRequest(byte sysid, byte compid, bool get_all)
        {
            this.sysid = sysid;
            this.compid = compid;
            this.get_all = get_all;
        }

        public static VehicleInfoGetRequest Deserialize(MessageDeserializer deserializer) => new VehicleInfoGetRequest(deserializer);

        private VehicleInfoGetRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sysid);
            deserializer.Read(out this.compid);
            deserializer.Read(out this.get_all);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sysid);
            serializer.Write(this.compid);
            serializer.Write(this.get_all);
        }

        public override string ToString()
        {
            return "VehicleInfoGetRequest: " +
            "\nsysid: " + sysid.ToString() +
            "\ncompid: " + compid.ToString() +
            "\nget_all: " + get_all.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
