//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class WaypointPushResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/WaypointPush";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public uint wp_transfered;

        public WaypointPushResponse()
        {
            this.success = false;
            this.wp_transfered = 0;
        }

        public WaypointPushResponse(bool success, uint wp_transfered)
        {
            this.success = success;
            this.wp_transfered = wp_transfered;
        }

        public static WaypointPushResponse Deserialize(MessageDeserializer deserializer) => new WaypointPushResponse(deserializer);

        private WaypointPushResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.wp_transfered);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.wp_transfered);
        }

        public override string ToString()
        {
            return "WaypointPushResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nwp_transfered: " + wp_transfered.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
