//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class WaypointPullResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/WaypointPull";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public uint wp_received;

        public WaypointPullResponse()
        {
            this.success = false;
            this.wp_received = 0;
        }

        public WaypointPullResponse(bool success, uint wp_received)
        {
            this.success = success;
            this.wp_received = wp_received;
        }

        public static WaypointPullResponse Deserialize(MessageDeserializer deserializer) => new WaypointPullResponse(deserializer);

        private WaypointPullResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.wp_received);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.wp_received);
        }

        public override string ToString()
        {
            return "WaypointPullResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nwp_received: " + wp_received.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
