//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class WaypointClearResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/WaypointClear";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public WaypointClearResponse()
        {
            this.success = false;
        }

        public WaypointClearResponse(bool success)
        {
            this.success = success;
        }

        public static WaypointClearResponse Deserialize(MessageDeserializer deserializer) => new WaypointClearResponse(deserializer);

        private WaypointClearResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "WaypointClearResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
