//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class WaypointPushRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/WaypointPush";
        public override string RosMessageName => k_RosMessageName;

        //  Send waypoints to device
        // 
        //   :start_index: will define a partial waypoint update. Set to 0 for full update
        // 
        //  Returns success status and transfered count
        public ushort start_index;
        public WaypointMsg[] waypoints;

        public WaypointPushRequest()
        {
            this.start_index = 0;
            this.waypoints = new WaypointMsg[0];
        }

        public WaypointPushRequest(ushort start_index, WaypointMsg[] waypoints)
        {
            this.start_index = start_index;
            this.waypoints = waypoints;
        }

        public static WaypointPushRequest Deserialize(MessageDeserializer deserializer) => new WaypointPushRequest(deserializer);

        private WaypointPushRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.start_index);
            deserializer.Read(out this.waypoints, WaypointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start_index);
            serializer.WriteLength(this.waypoints);
            serializer.Write(this.waypoints);
        }

        public override string ToString()
        {
            return "WaypointPushRequest: " +
            "\nstart_index: " + start_index.ToString() +
            "\nwaypoints: " + System.String.Join(", ", waypoints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
