//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class WaypointSetCurrentRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/WaypointSetCurrent";
        public override string RosMessageName => k_RosMessageName;

        //  Request set current waypoint
        // 
        //  wp_seq - index in waypoint array
        public ushort wp_seq;

        public WaypointSetCurrentRequest()
        {
            this.wp_seq = 0;
        }

        public WaypointSetCurrentRequest(ushort wp_seq)
        {
            this.wp_seq = wp_seq;
        }

        public static WaypointSetCurrentRequest Deserialize(MessageDeserializer deserializer) => new WaypointSetCurrentRequest(deserializer);

        private WaypointSetCurrentRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.wp_seq);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.wp_seq);
        }

        public override string ToString()
        {
            return "WaypointSetCurrentRequest: " +
            "\nwp_seq: " + wp_seq.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
