//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class OpenDroneIDSelfIDMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/OpenDroneIDSelfID";
        public override string RosMessageName => k_RosMessageName;

        //  Remote ID message - Self ID
        //  https://mavlink.io/en/messages/common.html#OPEN_DRONE_ID_SELF_ID
        //  [[[cog:
        //  import mavros_cog
        //  mavros_cog.idl_decl_enum('MAV_ODID_DESC_TYPE', 'DESC_TYPE_')
        //  ]]]
        //  MAV_ODID_DESC_TYPE
        public const byte DESC_TYPE_TEXT = 0; //  Free-form text description of the purpose of the flight.
        public const byte DESC_TYPE_EMERGENCY = 1; //  Optional additional clarification when status == MAV_ODID_STATUS_EMERGENCY.
        public const byte DESC_TYPE_EXTENDED_STATUS = 2; //  Optional additional clarification when status != MAV_ODID_STATUS_EMERGENCY.
        //  [[[end]]] (sum: CL9LfmadAd)
        public Std.HeaderMsg header;
        public string id_or_mac;
        public byte description_type;
        public string description;

        public OpenDroneIDSelfIDMsg()
        {
            this.header = new Std.HeaderMsg();
            this.id_or_mac = "";
            this.description_type = 0;
            this.description = "";
        }

        public OpenDroneIDSelfIDMsg(Std.HeaderMsg header, string id_or_mac, byte description_type, string description)
        {
            this.header = header;
            this.id_or_mac = id_or_mac;
            this.description_type = description_type;
            this.description = description;
        }

        public static OpenDroneIDSelfIDMsg Deserialize(MessageDeserializer deserializer) => new OpenDroneIDSelfIDMsg(deserializer);

        private OpenDroneIDSelfIDMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.id_or_mac);
            deserializer.Read(out this.description_type);
            deserializer.Read(out this.description);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.id_or_mac);
            serializer.Write(this.description_type);
            serializer.Write(this.description);
        }

        public override string ToString()
        {
            return "OpenDroneIDSelfIDMsg: " +
            "\nheader: " + header.ToString() +
            "\nid_or_mac: " + id_or_mac.ToString() +
            "\ndescription_type: " + description_type.ToString() +
            "\ndescription: " + description.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
