//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class OpenDroneIDSystemUpdateMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/OpenDroneIDSystemUpdate";
        public override string RosMessageName => k_RosMessageName;

        //  Remote ID message - System Update
        //  https://mavlink.io/en/messages/common.html#OPEN_DRONE_ID_SYSTEM_UPDATE
        public Std.HeaderMsg header;
        public int operator_latitude;
        public int operator_longitude;
        public float operator_altitude_geo;

        public OpenDroneIDSystemUpdateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.operator_latitude = 0;
            this.operator_longitude = 0;
            this.operator_altitude_geo = 0.0f;
        }

        public OpenDroneIDSystemUpdateMsg(Std.HeaderMsg header, int operator_latitude, int operator_longitude, float operator_altitude_geo)
        {
            this.header = header;
            this.operator_latitude = operator_latitude;
            this.operator_longitude = operator_longitude;
            this.operator_altitude_geo = operator_altitude_geo;
        }

        public static OpenDroneIDSystemUpdateMsg Deserialize(MessageDeserializer deserializer) => new OpenDroneIDSystemUpdateMsg(deserializer);

        private OpenDroneIDSystemUpdateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.operator_latitude);
            deserializer.Read(out this.operator_longitude);
            deserializer.Read(out this.operator_altitude_geo);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.operator_latitude);
            serializer.Write(this.operator_longitude);
            serializer.Write(this.operator_altitude_geo);
        }

        public override string ToString()
        {
            return "OpenDroneIDSystemUpdateMsg: " +
            "\nheader: " + header.ToString() +
            "\noperator_latitude: " + operator_latitude.ToString() +
            "\noperator_longitude: " + operator_longitude.ToString() +
            "\noperator_altitude_geo: " + operator_altitude_geo.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
