//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class OpenDroneIDOperatorIDMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/OpenDroneIDOperatorID";
        public override string RosMessageName => k_RosMessageName;

        //  Remote ID message - Operator ID
        //  https://mavlink.io/en/messages/common.html#OPEN_DRONE_ID_OPERATOR_ID
        //  [[[cog:
        //  import mavros_cog
        //  mavros_cog.idl_decl_enum('MAV_ODID_OPERATOR_ID_TYPE', 'ID_TYPE_')
        //  ]]]
        //  MAV_ODID_OPERATOR_ID_TYPE
        public const byte ID_TYPE_CAA = 0; //  CAA (Civil Aviation Authority) registered operator ID.
        //  [[[end]]] (sum: vhJAtj2LEB)
        public Std.HeaderMsg header;
        public string id_or_mac;
        public byte operator_id_type;
        public string operator_id;

        public OpenDroneIDOperatorIDMsg()
        {
            this.header = new Std.HeaderMsg();
            this.id_or_mac = "";
            this.operator_id_type = 0;
            this.operator_id = "";
        }

        public OpenDroneIDOperatorIDMsg(Std.HeaderMsg header, string id_or_mac, byte operator_id_type, string operator_id)
        {
            this.header = header;
            this.id_or_mac = id_or_mac;
            this.operator_id_type = operator_id_type;
            this.operator_id = operator_id;
        }

        public static OpenDroneIDOperatorIDMsg Deserialize(MessageDeserializer deserializer) => new OpenDroneIDOperatorIDMsg(deserializer);

        private OpenDroneIDOperatorIDMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.id_or_mac);
            deserializer.Read(out this.operator_id_type);
            deserializer.Read(out this.operator_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.id_or_mac);
            serializer.Write(this.operator_id_type);
            serializer.Write(this.operator_id);
        }

        public override string ToString()
        {
            return "OpenDroneIDOperatorIDMsg: " +
            "\nheader: " + header.ToString() +
            "\nid_or_mac: " + id_or_mac.ToString() +
            "\noperator_id_type: " + operator_id_type.ToString() +
            "\noperator_id: " + operator_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
