//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class SysStatusMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/SysStatus";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public uint sensors_present;
        public uint sensors_enabled;
        public uint sensors_health;
        public ushort load;
        public ushort voltage_battery;
        public short current_battery;
        public sbyte battery_remaining;
        public ushort drop_rate_comm;
        public ushort errors_comm;
        public ushort errors_count1;
        public ushort errors_count2;
        public ushort errors_count3;
        public ushort errors_count4;

        public SysStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.sensors_present = 0;
            this.sensors_enabled = 0;
            this.sensors_health = 0;
            this.load = 0;
            this.voltage_battery = 0;
            this.current_battery = 0;
            this.battery_remaining = 0;
            this.drop_rate_comm = 0;
            this.errors_comm = 0;
            this.errors_count1 = 0;
            this.errors_count2 = 0;
            this.errors_count3 = 0;
            this.errors_count4 = 0;
        }

        public SysStatusMsg(Std.HeaderMsg header, uint sensors_present, uint sensors_enabled, uint sensors_health, ushort load, ushort voltage_battery, short current_battery, sbyte battery_remaining, ushort drop_rate_comm, ushort errors_comm, ushort errors_count1, ushort errors_count2, ushort errors_count3, ushort errors_count4)
        {
            this.header = header;
            this.sensors_present = sensors_present;
            this.sensors_enabled = sensors_enabled;
            this.sensors_health = sensors_health;
            this.load = load;
            this.voltage_battery = voltage_battery;
            this.current_battery = current_battery;
            this.battery_remaining = battery_remaining;
            this.drop_rate_comm = drop_rate_comm;
            this.errors_comm = errors_comm;
            this.errors_count1 = errors_count1;
            this.errors_count2 = errors_count2;
            this.errors_count3 = errors_count3;
            this.errors_count4 = errors_count4;
        }

        public static SysStatusMsg Deserialize(MessageDeserializer deserializer) => new SysStatusMsg(deserializer);

        private SysStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.sensors_present);
            deserializer.Read(out this.sensors_enabled);
            deserializer.Read(out this.sensors_health);
            deserializer.Read(out this.load);
            deserializer.Read(out this.voltage_battery);
            deserializer.Read(out this.current_battery);
            deserializer.Read(out this.battery_remaining);
            deserializer.Read(out this.drop_rate_comm);
            deserializer.Read(out this.errors_comm);
            deserializer.Read(out this.errors_count1);
            deserializer.Read(out this.errors_count2);
            deserializer.Read(out this.errors_count3);
            deserializer.Read(out this.errors_count4);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.sensors_present);
            serializer.Write(this.sensors_enabled);
            serializer.Write(this.sensors_health);
            serializer.Write(this.load);
            serializer.Write(this.voltage_battery);
            serializer.Write(this.current_battery);
            serializer.Write(this.battery_remaining);
            serializer.Write(this.drop_rate_comm);
            serializer.Write(this.errors_comm);
            serializer.Write(this.errors_count1);
            serializer.Write(this.errors_count2);
            serializer.Write(this.errors_count3);
            serializer.Write(this.errors_count4);
        }

        public override string ToString()
        {
            return "SysStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nsensors_present: " + sensors_present.ToString() +
            "\nsensors_enabled: " + sensors_enabled.ToString() +
            "\nsensors_health: " + sensors_health.ToString() +
            "\nload: " + load.ToString() +
            "\nvoltage_battery: " + voltage_battery.ToString() +
            "\ncurrent_battery: " + current_battery.ToString() +
            "\nbattery_remaining: " + battery_remaining.ToString() +
            "\ndrop_rate_comm: " + drop_rate_comm.ToString() +
            "\nerrors_comm: " + errors_comm.ToString() +
            "\nerrors_count1: " + errors_count1.ToString() +
            "\nerrors_count2: " + errors_count2.ToString() +
            "\nerrors_count3: " + errors_count3.ToString() +
            "\nerrors_count4: " + errors_count4.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
