//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class TerrainReportMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/TerrainReport";
        public override string RosMessageName => k_RosMessageName;

        //  Message for TERRAIN_REPORT
        //  https://mavlink.io/en/messages/common.html#TERRAIN_REPORT
        public Std.HeaderMsg header;
        public double latitude;
        public double longitude;
        public ushort spacing;
        public float terrain_height;
        //  in meters, terrain height
        public float current_height;
        //  in meters, vehicle height above terrain
        public ushort pending;
        public ushort loaded;

        public TerrainReportMsg()
        {
            this.header = new Std.HeaderMsg();
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.spacing = 0;
            this.terrain_height = 0.0f;
            this.current_height = 0.0f;
            this.pending = 0;
            this.loaded = 0;
        }

        public TerrainReportMsg(Std.HeaderMsg header, double latitude, double longitude, ushort spacing, float terrain_height, float current_height, ushort pending, ushort loaded)
        {
            this.header = header;
            this.latitude = latitude;
            this.longitude = longitude;
            this.spacing = spacing;
            this.terrain_height = terrain_height;
            this.current_height = current_height;
            this.pending = pending;
            this.loaded = loaded;
        }

        public static TerrainReportMsg Deserialize(MessageDeserializer deserializer) => new TerrainReportMsg(deserializer);

        private TerrainReportMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
            deserializer.Read(out this.spacing);
            deserializer.Read(out this.terrain_height);
            deserializer.Read(out this.current_height);
            deserializer.Read(out this.pending);
            deserializer.Read(out this.loaded);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
            serializer.Write(this.spacing);
            serializer.Write(this.terrain_height);
            serializer.Write(this.current_height);
            serializer.Write(this.pending);
            serializer.Write(this.loaded);
        }

        public override string ToString()
        {
            return "TerrainReportMsg: " +
            "\nheader: " + header.ToString() +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString() +
            "\nspacing: " + spacing.ToString() +
            "\nterrain_height: " + terrain_height.ToString() +
            "\ncurrent_height: " + current_height.ToString() +
            "\npending: " + pending.ToString() +
            "\nloaded: " + loaded.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
