//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CommandIntRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CommandInt";
        public override string RosMessageName => k_RosMessageName;

        //  Generic COMMAND_INT
        public bool broadcast;
        //  send this command in broadcast mode
        public byte frame;
        public ushort command;
        public byte current;
        public byte autocontinue;
        public float param1;
        public float param2;
        public float param3;
        public float param4;
        public int x;
        //  latitude in deg * 1E7 or local x * 1E4 m
        public int y;
        //  longitude in deg * 1E7 or local y * 1E4 m
        public float z;
        //  altitude

        public CommandIntRequest()
        {
            this.broadcast = false;
            this.frame = 0;
            this.command = 0;
            this.current = 0;
            this.autocontinue = 0;
            this.param1 = 0.0f;
            this.param2 = 0.0f;
            this.param3 = 0.0f;
            this.param4 = 0.0f;
            this.x = 0;
            this.y = 0;
            this.z = 0.0f;
        }

        public CommandIntRequest(bool broadcast, byte frame, ushort command, byte current, byte autocontinue, float param1, float param2, float param3, float param4, int x, int y, float z)
        {
            this.broadcast = broadcast;
            this.frame = frame;
            this.command = command;
            this.current = current;
            this.autocontinue = autocontinue;
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.param4 = param4;
            this.x = x;
            this.y = y;
            this.z = z;
        }

        public static CommandIntRequest Deserialize(MessageDeserializer deserializer) => new CommandIntRequest(deserializer);

        private CommandIntRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.broadcast);
            deserializer.Read(out this.frame);
            deserializer.Read(out this.command);
            deserializer.Read(out this.current);
            deserializer.Read(out this.autocontinue);
            deserializer.Read(out this.param1);
            deserializer.Read(out this.param2);
            deserializer.Read(out this.param3);
            deserializer.Read(out this.param4);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.broadcast);
            serializer.Write(this.frame);
            serializer.Write(this.command);
            serializer.Write(this.current);
            serializer.Write(this.autocontinue);
            serializer.Write(this.param1);
            serializer.Write(this.param2);
            serializer.Write(this.param3);
            serializer.Write(this.param4);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
        }

        public override string ToString()
        {
            return "CommandIntRequest: " +
            "\nbroadcast: " + broadcast.ToString() +
            "\nframe: " + frame.ToString() +
            "\ncommand: " + command.ToString() +
            "\ncurrent: " + current.ToString() +
            "\nautocontinue: " + autocontinue.ToString() +
            "\nparam1: " + param1.ToString() +
            "\nparam2: " + param2.ToString() +
            "\nparam3: " + param3.ToString() +
            "\nparam4: " + param4.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
