//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class FileReadResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/FileRead";
        public override string RosMessageName => k_RosMessageName;

        public byte[] data;
        public bool success;
        public int r_errno;

        public FileReadResponse()
        {
            this.data = new byte[0];
            this.success = false;
            this.r_errno = 0;
        }

        public FileReadResponse(byte[] data, bool success, int r_errno)
        {
            this.data = data;
            this.success = success;
            this.r_errno = r_errno;
        }

        public static FileReadResponse Deserialize(MessageDeserializer deserializer) => new FileReadResponse(deserializer);

        private FileReadResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.success);
            deserializer.Read(out this.r_errno);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
            serializer.Write(this.success);
            serializer.Write(this.r_errno);
        }

        public override string ToString()
        {
            return "FileReadResponse: " +
            "\ndata: " + System.String.Join(", ", data.ToList()) +
            "\nsuccess: " + success.ToString() +
            "\nr_errno: " + r_errno.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
