//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class GimbalManagerPitchyawRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/GimbalManagerPitchyaw";
        public override string RosMessageName => k_RosMessageName;

        //  MAVLink commands: DO_GIMBAL_MANAGER_PITCHYAW
        //  https://mavlink.io/en/messages/common.html#MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW
        public float pitch;
        //  Pitch angle (positive to pitch up, relative to vehicle for FOLLOW mode, relative to world horizon for LOCK mode). (-180 to 180 deg)
        public float yaw;
        //  Yaw angle (positive to yaw to the right, relative to vehicle for FOLLOW mode, absolute to North for LOCK mode). (-180 to 180 deg)
        public float pitch_rate;
        //  Pitch rate (positive to pitch up). (deg/s)
        public float yaw_rate;
        //  Yaw rate (positive to yaw to the right). (deg/s)
        public uint flags;
        //  High level gimbal manager flags to use - See GIMBAL_MANAGER_FLAGS
        // GIMBAL_MANAGER_FLAGS
        public const uint GIMBAL_MANAGER_FLAGS_RETRACT = 1; //  Based on GIMBAL_DEVICE_FLAGS_RETRACT
        public const uint GIMBAL_MANAGER_FLAGS_NEUTRAL = 2; //  Based on GIMBAL_DEVICE_FLAGS_NEUTRAL
        public const uint GIMBAL_MANAGER_FLAGS_ROLL_LOCK = 4; //  Based on GIMBAL_DEVICE_FLAGS_ROLL_LOCK
        public const uint GIMBAL_MANAGER_FLAGS_PITCH_LOCK = 8; //  Based on GIMBAL_DEVICE_FLAGS_PITCH_LOCK
        public const uint GIMBAL_MANAGER_FLAGS_YAW_LOCK = 16; //  Based on GIMBAL_DEVICE_FLAGS_YAW_LOCK
        public byte gimbal_device_id;
        //  Component ID of gimbal device to address 
        //  (or 1-6 for non-MAVLink gimbal), 0 for all gimbal device
        //  components. Send command multiple times for more than
        //  one gimbal (but not all gimbals).  Default Mavlink gimbal 
        //  device ids: 154, 171-175

        public GimbalManagerPitchyawRequest()
        {
            this.pitch = 0.0f;
            this.yaw = 0.0f;
            this.pitch_rate = 0.0f;
            this.yaw_rate = 0.0f;
            this.flags = 0;
            this.gimbal_device_id = 0;
        }

        public GimbalManagerPitchyawRequest(float pitch, float yaw, float pitch_rate, float yaw_rate, uint flags, byte gimbal_device_id)
        {
            this.pitch = pitch;
            this.yaw = yaw;
            this.pitch_rate = pitch_rate;
            this.yaw_rate = yaw_rate;
            this.flags = flags;
            this.gimbal_device_id = gimbal_device_id;
        }

        public static GimbalManagerPitchyawRequest Deserialize(MessageDeserializer deserializer) => new GimbalManagerPitchyawRequest(deserializer);

        private GimbalManagerPitchyawRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.pitch_rate);
            deserializer.Read(out this.yaw_rate);
            deserializer.Read(out this.flags);
            deserializer.Read(out this.gimbal_device_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pitch);
            serializer.Write(this.yaw);
            serializer.Write(this.pitch_rate);
            serializer.Write(this.yaw_rate);
            serializer.Write(this.flags);
            serializer.Write(this.gimbal_device_id);
        }

        public override string ToString()
        {
            return "GimbalManagerPitchyawRequest: " +
            "\npitch: " + pitch.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\npitch_rate: " + pitch_rate.ToString() +
            "\nyaw_rate: " + yaw_rate.ToString() +
            "\nflags: " + flags.ToString() +
            "\ngimbal_device_id: " + gimbal_device_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
