//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class LogRequestDataRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/LogRequestData";
        public override string RosMessageName => k_RosMessageName;

        //  Request a chunk of a log
        // 
        //   :id: - log id from LogEntry message
        //   :offset: - offset into the log
        //   :count: - number of bytes to get
        public ushort id;
        public uint offset;
        public uint count;

        public LogRequestDataRequest()
        {
            this.id = 0;
            this.offset = 0;
            this.count = 0;
        }

        public LogRequestDataRequest(ushort id, uint offset, uint count)
        {
            this.id = id;
            this.offset = offset;
            this.count = count;
        }

        public static LogRequestDataRequest Deserialize(MessageDeserializer deserializer) => new LogRequestDataRequest(deserializer);

        private LogRequestDataRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.offset);
            deserializer.Read(out this.count);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.offset);
            serializer.Write(this.count);
        }

        public override string ToString()
        {
            return "LogRequestDataRequest: " +
            "\nid: " + id.ToString() +
            "\noffset: " + offset.ToString() +
            "\ncount: " + count.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
