//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ParamPushRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ParamPush";
        public override string RosMessageName => k_RosMessageName;

        //  Send current send
        // 
        //  Returns success status and param_transfered count
        //  XXX DEPRECATED: not used. param plugin listen to parameter changes

        public ParamPushRequest()
        {
        }
        public static ParamPushRequest Deserialize(MessageDeserializer deserializer) => new ParamPushRequest(deserializer);

        private ParamPushRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ParamPushRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
