//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ParamGetRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ParamGet";
        public override string RosMessageName => k_RosMessageName;

        //  Request parameter from attached device
        //  XXX DEPRECATED: use ros2 parameters api instead
        public string param_id;

        public ParamGetRequest()
        {
            this.param_id = "";
        }

        public ParamGetRequest(string param_id)
        {
            this.param_id = param_id;
        }

        public static ParamGetRequest Deserialize(MessageDeserializer deserializer) => new ParamGetRequest(deserializer);

        private ParamGetRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.param_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.param_id);
        }

        public override string ToString()
        {
            return "ParamGetRequest: " +
            "\nparam_id: " + param_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
