//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class StreamRateResponse : Message
    {
        public const string k_RosMessageName = "mavros_msgs/StreamRate";
        public override string RosMessageName => k_RosMessageName;


        public StreamRateResponse()
        {
        }
        public static StreamRateResponse Deserialize(MessageDeserializer deserializer) => new StreamRateResponse(deserializer);

        private StreamRateResponse(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "StreamRateResponse: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
