//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class StreamRateRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/StreamRate";
        public override string RosMessageName => k_RosMessageName;

        //  sets stream rate
        //  See REQUEST_DATA_STREAM message
        public const byte STREAM_ALL = 0;
        public const byte STREAM_RAW_SENSORS = 1;
        public const byte STREAM_EXTENDED_STATUS = 2;
        public const byte STREAM_RC_CHANNELS = 3;
        public const byte STREAM_RAW_CONTROLLER = 4;
        public const byte STREAM_POSITION = 6;
        public const byte STREAM_EXTRA1 = 10;
        public const byte STREAM_EXTRA2 = 11;
        public const byte STREAM_EXTRA3 = 12;
        public byte stream_id;
        public ushort message_rate;
        public bool on_off;

        public StreamRateRequest()
        {
            this.stream_id = 0;
            this.message_rate = 0;
            this.on_off = false;
        }

        public StreamRateRequest(byte stream_id, ushort message_rate, bool on_off)
        {
            this.stream_id = stream_id;
            this.message_rate = message_rate;
            this.on_off = on_off;
        }

        public static StreamRateRequest Deserialize(MessageDeserializer deserializer) => new StreamRateRequest(deserializer);

        private StreamRateRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stream_id);
            deserializer.Read(out this.message_rate);
            deserializer.Read(out this.on_off);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stream_id);
            serializer.Write(this.message_rate);
            serializer.Write(this.on_off);
        }

        public override string ToString()
        {
            return "StreamRateRequest: " +
            "\nstream_id: " + stream_id.ToString() +
            "\nmessage_rate: " + message_rate.ToString() +
            "\non_off: " + on_off.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
