//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class WaypointPullRequest : Message
    {
        public const string k_RosMessageName = "mavros_msgs/WaypointPull";
        public override string RosMessageName => k_RosMessageName;

        //  Requests waypoints from device
        // 
        //  Returns success status and received count

        public WaypointPullRequest()
        {
        }
        public static WaypointPullRequest Deserialize(MessageDeserializer deserializer) => new WaypointPullRequest(deserializer);

        private WaypointPullRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "WaypointPullRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
