//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class CellularStatusMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/CellularStatus";
        public override string RosMessageName => k_RosMessageName;

        // Follows https://mavlink.io/en/messages/common.html#CELLULAR_STATUS specification
        public byte status;
        public byte failure_reason;
        public byte type;
        public byte quality;
        public ushort mcc;
        public ushort mnc;
        public ushort lac;

        public CellularStatusMsg()
        {
            this.status = 0;
            this.failure_reason = 0;
            this.type = 0;
            this.quality = 0;
            this.mcc = 0;
            this.mnc = 0;
            this.lac = 0;
        }

        public CellularStatusMsg(byte status, byte failure_reason, byte type, byte quality, ushort mcc, ushort mnc, ushort lac)
        {
            this.status = status;
            this.failure_reason = failure_reason;
            this.type = type;
            this.quality = quality;
            this.mcc = mcc;
            this.mnc = mnc;
            this.lac = lac;
        }

        public static CellularStatusMsg Deserialize(MessageDeserializer deserializer) => new CellularStatusMsg(deserializer);

        private CellularStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.failure_reason);
            deserializer.Read(out this.type);
            deserializer.Read(out this.quality);
            deserializer.Read(out this.mcc);
            deserializer.Read(out this.mnc);
            deserializer.Read(out this.lac);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.failure_reason);
            serializer.Write(this.type);
            serializer.Write(this.quality);
            serializer.Write(this.mcc);
            serializer.Write(this.mnc);
            serializer.Write(this.lac);
        }

        public override string ToString()
        {
            return "CellularStatusMsg: " +
            "\nstatus: " + status.ToString() +
            "\nfailure_reason: " + failure_reason.ToString() +
            "\ntype: " + type.ToString() +
            "\nquality: " + quality.ToString() +
            "\nmcc: " + mcc.ToString() +
            "\nmnc: " + mnc.ToString() +
            "\nlac: " + lac.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
