//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ESCTelemetryMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ESCTelemetry";
        public override string RosMessageName => k_RosMessageName;

        //  APM ESC Telemetry as returned by BLHeli
        // 
        //  See:
        //  https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4
        //  https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8
        //  https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_9_TO_12
        public Std.HeaderMsg header;
        public ESCTelemetryItemMsg[] esc_telemetry;

        public ESCTelemetryMsg()
        {
            this.header = new Std.HeaderMsg();
            this.esc_telemetry = new ESCTelemetryItemMsg[0];
        }

        public ESCTelemetryMsg(Std.HeaderMsg header, ESCTelemetryItemMsg[] esc_telemetry)
        {
            this.header = header;
            this.esc_telemetry = esc_telemetry;
        }

        public static ESCTelemetryMsg Deserialize(MessageDeserializer deserializer) => new ESCTelemetryMsg(deserializer);

        private ESCTelemetryMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.esc_telemetry, ESCTelemetryItemMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.esc_telemetry);
            serializer.Write(this.esc_telemetry);
        }

        public override string ToString()
        {
            return "ESCTelemetryMsg: " +
            "\nheader: " + header.ToString() +
            "\nesc_telemetry: " + System.String.Join(", ", esc_telemetry.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
