//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mavros
{
    [Serializable]
    public class ManualControlMsg : Message
    {
        public const string k_RosMessageName = "mavros_msgs/ManualControl";
        public override string RosMessageName => k_RosMessageName;

        //  Manual Control state
        public Std.HeaderMsg header;
        public float x;
        public float y;
        public float z;
        public float r;
        public ushort buttons;
        //  -*- only available with MAVLink v2.0 -*-
        public ushort buttons2;
        public byte enabled_extensions;
        public float s;
        public float t;
        public float aux1;
        public float aux2;
        public float aux3;
        public float aux4;
        public float aux5;
        public float aux6;

        public ManualControlMsg()
        {
            this.header = new Std.HeaderMsg();
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.r = 0.0f;
            this.buttons = 0;
            this.buttons2 = 0;
            this.enabled_extensions = 0;
            this.s = 0.0f;
            this.t = 0.0f;
            this.aux1 = 0.0f;
            this.aux2 = 0.0f;
            this.aux3 = 0.0f;
            this.aux4 = 0.0f;
            this.aux5 = 0.0f;
            this.aux6 = 0.0f;
        }

        public ManualControlMsg(Std.HeaderMsg header, float x, float y, float z, float r, ushort buttons, ushort buttons2, byte enabled_extensions, float s, float t, float aux1, float aux2, float aux3, float aux4, float aux5, float aux6)
        {
            this.header = header;
            this.x = x;
            this.y = y;
            this.z = z;
            this.r = r;
            this.buttons = buttons;
            this.buttons2 = buttons2;
            this.enabled_extensions = enabled_extensions;
            this.s = s;
            this.t = t;
            this.aux1 = aux1;
            this.aux2 = aux2;
            this.aux3 = aux3;
            this.aux4 = aux4;
            this.aux5 = aux5;
            this.aux6 = aux6;
        }

        public static ManualControlMsg Deserialize(MessageDeserializer deserializer) => new ManualControlMsg(deserializer);

        private ManualControlMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.r);
            deserializer.Read(out this.buttons);
            deserializer.Read(out this.buttons2);
            deserializer.Read(out this.enabled_extensions);
            deserializer.Read(out this.s);
            deserializer.Read(out this.t);
            deserializer.Read(out this.aux1);
            deserializer.Read(out this.aux2);
            deserializer.Read(out this.aux3);
            deserializer.Read(out this.aux4);
            deserializer.Read(out this.aux5);
            deserializer.Read(out this.aux6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.r);
            serializer.Write(this.buttons);
            serializer.Write(this.buttons2);
            serializer.Write(this.enabled_extensions);
            serializer.Write(this.s);
            serializer.Write(this.t);
            serializer.Write(this.aux1);
            serializer.Write(this.aux2);
            serializer.Write(this.aux3);
            serializer.Write(this.aux4);
            serializer.Write(this.aux5);
            serializer.Write(this.aux6);
        }

        public override string ToString()
        {
            return "ManualControlMsg: " +
            "\nheader: " + header.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nr: " + r.ToString() +
            "\nbuttons: " + buttons.ToString() +
            "\nbuttons2: " + buttons2.ToString() +
            "\nenabled_extensions: " + enabled_extensions.ToString() +
            "\ns: " + s.ToString() +
            "\nt: " + t.ToString() +
            "\naux1: " + aux1.ToString() +
            "\naux2: " + aux2.ToString() +
            "\naux3: " + aux3.ToString() +
            "\naux4: " + aux4.ToString() +
            "\naux5: " + aux5.ToString() +
            "\naux6: " + aux6.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
